Fix job error detection

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -107,7 +107,7 @@ jobs:
       - run: |
           for file in resources/i18n/*.json; do
             echo "Validating $file"
-            jq empty "$file" || echo "$file is invalid"
+            jq empty "$file" || echo "$file is invalid" && exit 1
           done
 
   binaries:
